import React, { useState } from 'react';
import { FiShield, FiLock, FiEyeOff, FiDatabase, FiUser, FiTrash2 } from 'react-icons/fi';
import { useAuth } from '../context/AuthContext';
import toast from 'react-hot-toast';

const privacyPoints = [
  {
    icon: FiEyeOff,
    title: 'No Medical Records Required',
    color: '#0d9488',
    bg: '#f0fdfa',
    description:
      'VitalIQ Health never asks for prescriptions, lab reports, doctor notes, or any certified medical documents. Everything we use is based on simple lifestyle inputs — sleep, meals, activity, and stress.'
  },
  {
    icon: FiLock,
    title: 'Wellness Streaks Use Anonymized Names',
    color: '#8b5cf6',
    bg: '#f5f3ff',
    description:
      'The Wellness Streaks community leaderboard displays anonymized display names only. Your real name, email, or any personal health data is never visible to other users.'
  },
  {
    icon: FiDatabase,
    title: 'AI Insights Are Not Stored as Medical Records',
    color: '#0ea5e9',
    bg: '#f0f9ff',
    description:
      'Wellness insights generated by the Gemini AI are not stored as medical records. They are lifestyle estimates for personal awareness only and do not constitute any form of diagnosis or clinical assessment.'
  },
  {
    icon: FiUser,
    title: 'Guest Mode — Zero Data Retention',
    color: '#f59e0b',
    bg: '#fffbeb',
    description:
      'Guest users can explore VitalIQ Health without creating an account. Guest wellness checks are temporary and are not saved to our database. No personally identifiable information is collected in guest mode.'
  },
  {
    icon: FiShield,
    title: 'Your Data Is Yours',
    color: '#10b981',
    bg: '#f0fdf4',
    description:
      'You control your account data. Registered users can request account deletion at any time. When an account is deleted, all associated health logs and personal information are permanently removed from our systems.'
  },
  {
    icon: FiTrash2,
    title: 'No Third-Party Data Selling',
    color: '#ef4444',
    bg: '#fef2f2',
    description:
      'VitalIQ Health does not sell, rent, or share your personal wellness data with third parties for marketing purposes. Data shared with the Gemini API is used solely for generating your personalized wellness insights.'
  }
];

const Privacy = () => {
  const { user } = useAuth();
  const isGuest = !user || user.isGuest || user.role === 'guest' || user.isMockGoogle || user.role === 'demo';

  const checkGuestData = () => {
    const onboarding = localStorage.getItem('vitaliq_onboarding');
    const checks = localStorage.getItem('vitaliq_wellness_checks');
    const checkins = localStorage.getItem('vitaliq_weekly_checkins');
    const habits = localStorage.getItem('vitaliq_habit_history');
    return !!(onboarding || checks || checkins || habits);
  };

  const [hasGuestData, setHasGuestData] = useState(checkGuestData());

  const handleClearGuestData = () => {
    const confirmDelete = window.confirm('Are you sure you want to delete all guest wellness history and preferences from this device? This action cannot be undone.');
    if (!confirmDelete) return;

    localStorage.removeItem('vitaliq_onboarding');
    localStorage.removeItem('vitaliq_wellness_checks');
    localStorage.removeItem('vitaliq_weekly_checkins');
    localStorage.removeItem('vitaliq_habit_history');
    localStorage.removeItem('vitaliq_latest_checkin');
    
    // Clear all habit and daily action daily logs
    Object.keys(localStorage).forEach(key => {
      if (key.startsWith('vitaliq_daily_actions_') || key.startsWith('vitaliq_habits_')) {
        localStorage.removeItem(key);
      }
    });

    setHasGuestData(false);
    toast.success('All guest data successfully removed from this device! 🗑️');
  };
  return (
    <div className="page-enter">
      {/* Page Header */}
      <div style={{ marginBottom: '36px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '14px', marginBottom: '10px' }}>
          <div style={{
            width: '50px', height: '50px', borderRadius: '16px',
            background: 'linear-gradient(135deg, #0d9488, #10b981)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            boxShadow: '0 4px 14px rgba(13,148,136,0.25)'
          }}>
            <FiShield size={24} color="white" />
          </div>
          <div>
            <h1 style={{ fontSize: '1.8rem', fontWeight: 900, marginBottom: '3px' }}>
              <span className="gradient-text">Privacy & Data Safety</span> 🔒
            </h1>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', margin: 0 }}>
              How VitalIQ Health protects your wellness data and respects your privacy.
            </p>
          </div>
        </div>
      </div>

      {/* Top disclaimer card */}
      <div style={{
        padding: '22px 28px',
        marginBottom: '36px',
        background: 'linear-gradient(135deg, #f0fdfa 0%, #ecfdf5 100%)',
        border: '1px solid #a7f3d0',
        borderRadius: '18px',
        display: 'flex',
        gap: '14px',
        alignItems: 'flex-start'
      }}>
        <FiShield size={22} color="#0d9488" style={{ flexShrink: 0, marginTop: '2px' }} />
        <div>
          <p style={{ fontSize: '0.95rem', color: '#065f46', fontWeight: 600, marginBottom: '6px' }}>
            VitalIQ Health is a wellness awareness platform — not a medical service.
          </p>
          <p style={{ fontSize: '0.88rem', color: '#047857', lineHeight: 1.7, margin: 0 }}>
            It provides wellness insights and lifestyle wellness estimates only. It does not diagnose, treat, cure, or replace professional medical advice.
            For medical concerns, consult a qualified healthcare professional.
          </p>
        </div>
      </div>

      {/* Privacy cards */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
        gap: '20px',
        marginBottom: '40px'
      }}>
        {privacyPoints.map(({ icon: Icon, title, color, bg, description }) => (
          <div key={title} className="medical-card" style={{ padding: '28px' }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px' }}>
              <div style={{
                width: '46px', height: '46px', borderRadius: '13px',
                background: bg, display: 'flex', alignItems: 'center',
                justifyContent: 'center', flexShrink: 0
              }}>
                <Icon size={22} color={color} />
              </div>
              <div>
                <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '8px', color: 'var(--text-primary)' }}>
                  {title}
                </h3>
                <p style={{ fontSize: '0.87rem', color: 'var(--text-secondary)', lineHeight: 1.65 }}>
                  {description}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Data Management / Privacy Controls */}
      <div className="medical-card" style={{ padding: '28px', marginBottom: '32px' }}>
        <h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: 'var(--text-primary)', marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <FiDatabase /> Data Control Center
        </h3>
        
        {isGuest ? (
          <div>
            {hasGuestData ? (
              <div>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: 1.6, marginBottom: '20px' }}>
                  As a guest, your progress is saved on this device only. You can clear guest data anytime from this device.
                </p>
                <button
                  onClick={handleClearGuestData}
                  className="btn-primary"
                  style={{
                    background: '#dc2626',
                    borderColor: '#dc2626',
                    color: 'white',
                    fontWeight: 700,
                    padding: '12px 24px',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px',
                    cursor: 'pointer'
                  }}
                >
                  <FiTrash2 /> Clear Guest Data from Device
                </button>
              </div>
            ) : (
              <div style={{ padding: '16px', background: '#f8fafc', borderRadius: '12px', border: '1px solid #e2e8f0', textAlign: 'center', color: 'var(--text-muted)', fontSize: '0.85rem', fontWeight: 600 }}>
                No guest data found on this device.
              </div>
            )}
          </div>
        ) : (
          <div>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: 1.6, marginBottom: '0' }}>
              Account data controls are planned for the next release.
            </p>
          </div>
        )}
      </div>

      {/* Footer note */}
      <div style={{
        padding: '18px 24px',
        background: '#f8fafc',
        border: '1px solid #e2e8f0',
        borderRadius: '14px',
        textAlign: 'center'
      }}>
        <p style={{ fontSize: '0.82rem', color: '#64748b', lineHeight: 1.7, margin: 0 }}>
          Last updated: May 2026 · VitalIQ Health, an AI-Assisted Wellness Platform.{' '}
          For questions about data privacy, contact us via the support channel.
        </p>
      </div>
    </div>
  );
};

export default Privacy;
